name: Check for White Smoke

on:
  schedule:
    - cron: '*/15 * * * *'  # every 15 minutes
  workflow_dispatch:       # manual trigger for testing

jobs:
  white-smoke-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run smoke check
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "Running in TEST_MODE"
            TEST_MODE=true node check_rss.js
          else
            node check_rss.js
          fi
        env:
          PUSHOVER_USER_KEY: ${{ secrets.PUSHOVER_USER_KEY }}
          PUSHOVER_APP_TOKEN: ${{ secrets.PUSHOVER_APP_TOKEN }}